path: .

train: datasets/BDD100K/splits/train.txt
val: datasets/BDD100K/splits/val.txt
test: datasets/BDD100K/weather_subsets/night_raw.txt

names:
  0: person
  1: rider
  2: car
  3: truck
  4: train
  5: bike
